### ISSUE TITLE
Cannot import H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\zh-CN module for custom nodes: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\zh-CN\\__init__.py'

### ISSUE THREAD

**Issue by bxdsjs** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#120]
why？？？？

Total VRAM 6144 MB, total RAM 16236 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints H:\ai\novelai-webui-aki-v2_2\models/Stable-diffusion
Adding extra search path configs H:\ai\novelai-webui-aki-v2_2\models/Stable-diffusion
Adding extra search path vae H:\ai\novelai-webui-aki-v2_2\models/VAE
Adding extra search path loras H:\ai\novelai-webui-aki-v2_2\models/Lora
Adding extra search path loras H:\ai\novelai-webui-aki-v2_2\models/LyCORIS
Adding extra search path upscale_models H:\ai\novelai-webui-aki-v2_2\models/ESRGAN
Adding extra search path upscale_models H:\ai\novelai-webui-aki-v2_2\models/RealESRGAN
Adding extra search path upscale_models H:\ai\novelai-webui-aki-v2_2\models/SwinIR
Adding extra search path embeddings H:\ai\novelai-webui-aki-v2_2\embeddings
Adding extra search path hypernetworks H:\ai\novelai-webui-aki-v2_2\models/hypernetworks
Adding extra search path controlnet H:\ai\novelai-webui-aki-v2_2\models/ControlNet
Traceback (most recent call last):
  File "H:\ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\zh-TW\\__init__.py'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\zh-TW module for custom nodes: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\zh-TW\\__init__.py'
[agl/register error]: [WinError 1] 函数不正确。
Traceback (most recent call last):
  File "H:\ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\example\\__init__.py'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\example module for custom nodes: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\example\\__init__.py'
Traceback (most recent call last):
  File "H:\ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ja-JP\\__init__.py'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ja-JP module for custom nodes: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ja-JP\\__init__.py'
Traceback (most recent call last):
  File "H:\ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ko-KR\\__init__.py'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ko-KR module for custom nodes: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ko-KR\\__init__.py'
Traceback (most recent call last):
  File "H:\ai\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\zh-CN\\__init__.py'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\zh-CN module for custom nodes: [Errno 2] No such file or directory: 'H:\\ai\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\zh-CN\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\zh-CN
   0.0 seconds (IMPORT FAILED): H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ja-JP
   0.0 seconds (IMPORT FAILED): H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ko-KR
   0.0 seconds (IMPORT FAILED): H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\example
   0.0 seconds (IMPORT FAILED): H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\zh-TW
   0.1 seconds: H:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\__init__.py

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by KarryCharon** [comment]
@bxdsjs Wrong File/Dir location. You should put the whole AIGODLIKE-ComfyUI-Translation directory into custom_nodes instead of extract the subdir such as zh-CN etc into the custom_nodes folder.

**Comment by KarryCharon** [comment]
@bxdsjs Correct installation path may be like this:
```
ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation\
                         |-zh-CN
                         |-ja-JP
                         |-ko-KR
                         |-example
                         |-zh-TW
```
Not like this:
```
ComfyUI\custom_nodes\
        |-zh-CN
        |-ja-JP
        |-ko-KR
        |-example
        |-zh-TW
```
